[project]
name = "dbt-dummy-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dbt-core>=1.9.8",
    "dbt-duckdb==1.9.3",
    "duckdb>=1.3.0",
    "numpy>=2.2.6",
    "polars>=1.30.0",
    "pyarrow>=20.0.0",
]
